name = "DevilSpawn"
uuid = "47b06df2-a16c-4c63-aa5d-786000e9a906"
authors = ["Malte Sandstede <malte@sandstede.com>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
